/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.sonar;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean isEqual(String var1, String var2) {
        return var1 == var2;
    }

}
